#pragma kernel PredictPositions;
#pragma kernel ComputeDensity
#pragma kernel ComputePressureForce;
#pragma kernel Integrate;
#pragma kernel ResolveBoundaryCollisions;

RWStructuredBuffer<float3> predictedPositions;
RWStructuredBuffer<float3> positions;
RWStructuredBuffer<float3> velocities;
RWStructuredBuffer<float> densities;

int nParticles;
float gravity;
float smoothingRadius;
float mass;
vector simulationSize;
float dt;
float pressureMultiplier;
float targetDensity;
float viscosityStrength;

static const float damping = 0.95f;


// uses the poly6 smoothing kernel
float SmoothingKernel(float distance, float radius)
{
    if (distance >= radius) return 0;
    
    float volume = (3.14159265359f * pow(radius, 4)) / 6;
    return (radius - distance) * (radius - distance) / volume;
}

float3 CalculateViscosityForce(int particleIndex)
{
    float3 viscosityForce = float3(0, 0, 0);

    for (int otherParticleIndex = 0; otherParticleIndex < nParticles; otherParticleIndex++)
    {
        if (particleIndex == otherParticleIndex) continue;

        float3 offset = predictedPositions[otherParticleIndex] - predictedPositions[particleIndex];
        float distance = length(offset);

        if (distance > smoothingRadius) continue;

        float density = max(densities[otherParticleIndex], 0.0001f);
        float influence = SmoothingKernel(distance, smoothingRadius);

        viscosityForce += 
            (velocities[otherParticleIndex] - velocities[particleIndex]) *
            influence *
            mass / density;
    }

    return viscosityForce;
}

// returns the calculated density on a given sample point
float CalculateDensity(float3 position)
{
    float density = 0;

    for (int i = 0; i < nParticles; i++)
    {
        float distance = length(position - predictedPositions[i]);
        density += mass * SmoothingKernel(distance, smoothingRadius);
    }

    return density;
}

float CalculatePressure(float density)
{
    return max(0.0f, (density - targetDensity) * pressureMultiplier);
}

float CalculateSharedPressure(float densityA, float densityB)
{
    float pressureA = CalculatePressure(densityA);
    float pressureB = CalculatePressure(densityB);
    return (pressureA + pressureB) / 2;
}

// returns the gradient of the spiky kernel
float SmoothingKernelDerivative(float distance, float radius)
{
    if (distance >= radius) return 0;
    
    float scale = 12 / (pow(radius, 4) * 3.14159265359f);
    return (distance - radius) * scale;
}

float3  CalculatePressureForce(int particleIndex)
{
    float3 pressureForce = float3(0,0,0);

    for (int otherParticleIndex = 0; otherParticleIndex < nParticles; otherParticleIndex++)
    {
        if (particleIndex == otherParticleIndex) continue;

        float3 offset = predictedPositions[otherParticleIndex] - predictedPositions[particleIndex];
        float distance = length(offset);
        if (distance < 0.0001f) continue;
        float3 direction = offset / distance;
            
        float slope = SmoothingKernelDerivative(distance, smoothingRadius);
        float density = densities[otherParticleIndex];
        float sharedPressure = CalculateSharedPressure(density, densities[particleIndex]);
        pressureForce += sharedPressure * direction * slope * mass / density;
    }

    return pressureForce;
}

[numthreads(64,1,1)]
void PredictPositions(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)nParticles) return;
    
    velocities[id.x] += float3(0,-1,0) * gravity * dt;
    predictedPositions[id.x] = positions[id.x] + velocities[id.x] * dt;
}

[numthreads(64,1,1)]
void ComputeDensity (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)nParticles) return;
    
    densities[id.x] = CalculateDensity(predictedPositions[id.x]);
}

[numthreads(64,1,1)]
void ComputePressureForce(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)nParticles) return;
    
    float density = max(densities[id.x], 0.0001f);
    
    float3 pressureForce = CalculatePressureForce(id.x);
    float3 pressureAcceleration = pressureForce / density;
    velocities[id.x] += pressureAcceleration * dt;
    
    float3 viscosityForce = CalculateViscosityForce(id.x);
    velocities[id.x] += viscosityForce * viscosityStrength * dt;
}

[numthreads(64,1,1)]
void Integrate(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)nParticles) return;
    velocities[id.x] *= 0.999f;
    positions[id.x] += velocities[id.x] * dt;
    
    
    // Boundary conditions
    if (positions[id.x].x <= 0.0 || positions[id.x].x >= simulationSize.x)
    {
        velocities[id.x].x *= -damping;
        positions[id.x].x = clamp(positions[id.x].x, 0.0, simulationSize.x);
    }

    if (positions[id.x].y <= 0.0 || positions[id.x].y >= simulationSize.y)
    {
        velocities[id.x].y *= -damping;
        positions[id.x].y = clamp(positions[id.x].y, 0.0, simulationSize.y);
    }
}

[numthreads(64,1,1)]
void ResolveBoundaryCollisions(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)nParticles) return;
    positions[id.x] = positions[id.x];
}
